(cl:in-package dw_listener-msg)
(cl:export '(TAGADDRESS-VAL
          TAGADDRESS
          RANGENUM-VAL
          RANGENUM
          TIMEOFRECEPTION-VAL
          TIMEOFRECEPTION
          DISTANCE-VAL
          DISTANCE
          DEGREES-VAL
          DEGREES
          XCOORD-VAL
          XCOORD
          YCOORD-VAL
          YCOORD
          XCOORDFILTERED-VAL
          XCOORDFILTERED
          YCOORDFILTERED-VAL
          YCOORDFILTERED
          CLOCKOFFSET-VAL
          CLOCKOFFSET
          SERVICEDATA-VAL
          SERVICEDATA
          XACCEL-VAL
          XACCEL
          YACCEL-VAL
          YACCEL
          ZACCEL-VAL
          ZACCEL
))